// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBookRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type CreateBookResponse struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookResponse) Reset()         { *m = CreateBookResponse{} }
func (m *CreateBookResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookResponse) ProtoMessage()    {}
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *CreateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookResponse.Unmarshal(m, b)
}
func (m *CreateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookResponse.Merge(m, src)
}
func (m *CreateBookResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookResponse.Size(m)
}
func (m *CreateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookResponse proto.InternalMessageInfo

func (m *CreateBookResponse) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type DeleteBookRequest struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(m, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type DeleteBookResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookResponse) Reset()         { *m = DeleteBookResponse{} }
func (m *DeleteBookResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookResponse) ProtoMessage()    {}
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *DeleteBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookResponse.Unmarshal(m, b)
}
func (m *DeleteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookResponse.Merge(m, src)
}
func (m *DeleteBookResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookResponse.Size(m)
}
func (m *DeleteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookResponse proto.InternalMessageInfo

func (m *DeleteBookResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetBookRequest struct {
	BookId               string                `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *GetBookRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type BatchGetBookRequest struct {
	BookIds              []string              `protobuf:"bytes,1,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BatchGetBookRequest) Reset()         { *m = BatchGetBookRequest{} }
func (m *BatchGetBookRequest) String() string { return proto.CompactTextString(m) }
func (*BatchGetBookRequest) ProtoMessage()    {}
func (*BatchGetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{5}
}

func (m *BatchGetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetBookRequest.Unmarshal(m, b)
}
func (m *BatchGetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetBookRequest.Marshal(b, m, deterministic)
}
func (m *BatchGetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetBookRequest.Merge(m, src)
}
func (m *BatchGetBookRequest) XXX_Size() int {
	return xxx_messageInfo_BatchGetBookRequest.Size(m)
}
func (m *BatchGetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetBookRequest proto.InternalMessageInfo

func (m *BatchGetBookRequest) GetBookIds() []string {
	if m != nil {
		return m.BookIds
	}
	return nil
}

func (m *BatchGetBookRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type BatchGetBookResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetBookResponse) Reset()         { *m = BatchGetBookResponse{} }
func (m *BatchGetBookResponse) String() string { return proto.CompactTextString(m) }
func (*BatchGetBookResponse) ProtoMessage()    {}
func (*BatchGetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{6}
}

func (m *BatchGetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetBookResponse.Unmarshal(m, b)
}
func (m *BatchGetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetBookResponse.Marshal(b, m, deterministic)
}
func (m *BatchGetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetBookResponse.Merge(m, src)
}
func (m *BatchGetBookResponse) XXX_Size() int {
	return xxx_messageInfo_BatchGetBookResponse.Size(m)
}
func (m *BatchGetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetBookResponse proto.InternalMessageInfo

func (m *BatchGetBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Book struct {
	SNIC                 string   `protobuf:"bytes,1,opt,name=SNIC,proto3" json:"SNIC,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Publisher            string   `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PublishDuration      int64    `protobuf:"varint,4,opt,name=publish_duration,json=publishDuration,proto3" json:"publish_duration,omitempty"`
	Author               *Author  `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Rate                 float32  `protobuf:"fixed32,8,opt,name=rate,proto3" json:"rate,omitempty"`
	CreateTime           int64    `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{7}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetSNIC() string {
	if m != nil {
		return m.SNIC
	}
	return ""
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *Book) GetPublishDuration() int64 {
	if m != nil {
		return m.PublishDuration
	}
	return 0
}

func (m *Book) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Book) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Book) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Book) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type Author struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EnglishName          string   `protobuf:"bytes,2,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{8}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Author) GetEnglishName() string {
	if m != nil {
		return m.EnglishName
	}
	return ""
}

type UpdateBookRequest struct {
	UserId               string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{9}
}

func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(m, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateBookRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type UpdateBookResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookResponse) Reset()         { *m = UpdateBookResponse{} }
func (m *UpdateBookResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBookResponse) ProtoMessage()    {}
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{10}
}

func (m *UpdateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookResponse.Unmarshal(m, b)
}
func (m *UpdateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookResponse.Merge(m, src)
}
func (m *UpdateBookResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBookResponse.Size(m)
}
func (m *UpdateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookResponse proto.InternalMessageInfo

func (m *UpdateBookResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListBooksRequest struct {
	Order                string   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Parent               string   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{11}
}

func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (m *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(m, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

func (m *ListBooksRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *ListBooksRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListBooksRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListBooksRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type ListBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{12}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *ListBooksResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type UndeleteBookRequest struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UndeleteBookRequest) Reset()         { *m = UndeleteBookRequest{} }
func (m *UndeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*UndeleteBookRequest) ProtoMessage()    {}
func (*UndeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{13}
}

func (m *UndeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UndeleteBookRequest.Unmarshal(m, b)
}
func (m *UndeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UndeleteBookRequest.Marshal(b, m, deterministic)
}
func (m *UndeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndeleteBookRequest.Merge(m, src)
}
func (m *UndeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_UndeleteBookRequest.Size(m)
}
func (m *UndeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UndeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UndeleteBookRequest proto.InternalMessageInfo

func (m *UndeleteBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type UndeleteBookResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UndeleteBookResponse) Reset()         { *m = UndeleteBookResponse{} }
func (m *UndeleteBookResponse) String() string { return proto.CompactTextString(m) }
func (*UndeleteBookResponse) ProtoMessage()    {}
func (*UndeleteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{14}
}

func (m *UndeleteBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UndeleteBookResponse.Unmarshal(m, b)
}
func (m *UndeleteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UndeleteBookResponse.Marshal(b, m, deterministic)
}
func (m *UndeleteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndeleteBookResponse.Merge(m, src)
}
func (m *UndeleteBookResponse) XXX_Size() int {
	return xxx_messageInfo_UndeleteBookResponse.Size(m)
}
func (m *UndeleteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UndeleteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UndeleteBookResponse proto.InternalMessageInfo

func (m *UndeleteBookResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SearchBookRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBookRequest) Reset()         { *m = SearchBookRequest{} }
func (m *SearchBookRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBookRequest) ProtoMessage()    {}
func (*SearchBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{15}
}

func (m *SearchBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBookRequest.Unmarshal(m, b)
}
func (m *SearchBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBookRequest.Marshal(b, m, deterministic)
}
func (m *SearchBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBookRequest.Merge(m, src)
}
func (m *SearchBookRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBookRequest.Size(m)
}
func (m *SearchBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBookRequest proto.InternalMessageInfo

type SearchBookResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchBookResponse) Reset()         { *m = SearchBookResponse{} }
func (m *SearchBookResponse) String() string { return proto.CompactTextString(m) }
func (*SearchBookResponse) ProtoMessage()    {}
func (*SearchBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{16}
}

func (m *SearchBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBookResponse.Unmarshal(m, b)
}
func (m *SearchBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBookResponse.Marshal(b, m, deterministic)
}
func (m *SearchBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBookResponse.Merge(m, src)
}
func (m *SearchBookResponse) XXX_Size() int {
	return xxx_messageInfo_SearchBookResponse.Size(m)
}
func (m *SearchBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBookResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateBookRequest)(nil), "heyifeng.book.v1.CreateBookRequest")
	proto.RegisterType((*CreateBookResponse)(nil), "heyifeng.book.v1.CreateBookResponse")
	proto.RegisterType((*DeleteBookRequest)(nil), "heyifeng.book.v1.DeleteBookRequest")
	proto.RegisterType((*DeleteBookResponse)(nil), "heyifeng.book.v1.DeleteBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "heyifeng.book.v1.GetBookRequest")
	proto.RegisterType((*BatchGetBookRequest)(nil), "heyifeng.book.v1.BatchGetBookRequest")
	proto.RegisterType((*BatchGetBookResponse)(nil), "heyifeng.book.v1.BatchGetBookResponse")
	proto.RegisterType((*Book)(nil), "heyifeng.book.v1.Book")
	proto.RegisterType((*Author)(nil), "heyifeng.book.v1.Author")
	proto.RegisterType((*UpdateBookRequest)(nil), "heyifeng.book.v1.UpdateBookRequest")
	proto.RegisterType((*UpdateBookResponse)(nil), "heyifeng.book.v1.UpdateBookResponse")
	proto.RegisterType((*ListBooksRequest)(nil), "heyifeng.book.v1.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "heyifeng.book.v1.ListBooksResponse")
	proto.RegisterType((*UndeleteBookRequest)(nil), "heyifeng.book.v1.UndeleteBookRequest")
	proto.RegisterType((*UndeleteBookResponse)(nil), "heyifeng.book.v1.UndeleteBookResponse")
	proto.RegisterType((*SearchBookRequest)(nil), "heyifeng.book.v1.SearchBookRequest")
	proto.RegisterType((*SearchBookResponse)(nil), "heyifeng.book.v1.SearchBookResponse")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xd3, 0x4a,
	0x10, 0x4d, 0xda, 0xc4, 0x89, 0x27, 0xbd, 0xb7, 0xcd, 0x36, 0xea, 0xf5, 0xcd, 0xbd, 0x88, 0xb0,
	0x85, 0x2a, 0xa0, 0xe2, 0x96, 0xf2, 0xc4, 0x53, 0x45, 0x5b, 0x40, 0x95, 0xa0, 0x42, 0x4e, 0x8b,
	0x04, 0x2f, 0x96, 0x13, 0x4f, 0x12, 0x2b, 0x89, 0x1d, 0x76, 0xed, 0x0a, 0x2a, 0x7e, 0x29, 0xbf,
	0x84, 0x47, 0xb4, 0xeb, 0x4d, 0xe3, 0x74, 0xdd, 0x0f, 0xd1, 0xb7, 0x9d, 0xb3, 0xe3, 0x33, 0x67,
	0x67, 0x8f, 0x67, 0x01, 0xba, 0x51, 0x34, 0xb2, 0xa7, 0x2c, 0x8a, 0x23, 0xb2, 0x36, 0xc4, 0xef,
	0x41, 0x1f, 0xc3, 0x81, 0x2d, 0xc1, 0xf3, 0x17, 0xcd, 0xd6, 0x20, 0x8a, 0x06, 0x63, 0xdc, 0x91,
	0xfb, 0xdd, 0xa4, 0xbf, 0xd3, 0x0f, 0x70, 0xec, 0xbb, 0x13, 0x8f, 0xab, 0x6f, 0xe8, 0x3e, 0xd4,
	0x0f, 0x19, 0x7a, 0x31, 0x1e, 0x44, 0xd1, 0xc8, 0xc1, 0xaf, 0x09, 0xf2, 0x98, 0x3c, 0x83, 0x92,
	0x60, 0xb0, 0x8a, 0xad, 0x62, 0xbb, 0xb6, 0xb7, 0x61, 0x5f, 0xe5, 0xb5, 0x65, 0xb2, 0xcc, 0xa1,
	0xcf, 0x81, 0x64, 0x09, 0xf8, 0x34, 0x0a, 0x39, 0x92, 0x7f, 0xa0, 0x22, 0x76, 0xdd, 0xc0, 0x97,
	0x24, 0xa6, 0x63, 0x88, 0xf0, 0xd8, 0xa7, 0xdb, 0x50, 0x3f, 0xc2, 0x31, 0x2e, 0xd6, 0xbb, 0x36,
	0xdb, 0x06, 0x92, 0xcd, 0x56, 0xe4, 0x16, 0x54, 0x78, 0xd2, 0xeb, 0x21, 0xe7, 0x32, 0xbd, 0xea,
	0xcc, 0x42, 0xea, 0xc3, 0xdf, 0xef, 0x30, 0xbe, 0x0b, 0x35, 0x79, 0x05, 0x30, 0x6f, 0x86, 0xb5,
	0x24, 0x4f, 0xda, 0xb4, 0xd3, 0x7e, 0xd9, 0xb3, 0x7e, 0xd9, 0x6f, 0x45, 0xca, 0x07, 0x8f, 0x8f,
	0x1c, 0xb3, 0x3f, 0x5b, 0xd2, 0x11, 0xac, 0x1f, 0x78, 0x71, 0x6f, 0x78, 0xa5, 0xd4, 0xbf, 0x50,
	0x55, 0xa5, 0x84, 0xae, 0xe5, 0xb6, 0xe9, 0x54, 0xd2, 0x5a, 0xfc, 0x3e, 0xc5, 0x8e, 0xa0, 0xb1,
	0x58, 0x4c, 0x35, 0x61, 0x1b, 0xca, 0x82, 0x3d, 0x2d, 0x75, 0xfd, 0x25, 0xa5, 0x49, 0xf4, 0x57,
	0x11, 0x4a, 0x22, 0x26, 0x04, 0x4a, 0x9d, 0x93, 0xe3, 0x43, 0xd5, 0x0c, 0xb9, 0x16, 0x58, 0xe8,
	0x4d, 0x50, 0xea, 0x32, 0x1d, 0xb9, 0x26, 0xff, 0x83, 0x39, 0x4d, 0xba, 0xe3, 0x80, 0x0f, 0x91,
	0x59, 0xcb, 0x72, 0x63, 0x0e, 0x90, 0xa7, 0xb0, 0xa6, 0x02, 0xd7, 0x4f, 0x98, 0x17, 0x07, 0x51,
	0x68, 0x95, 0x5a, 0xc5, 0xf6, 0xb2, 0xb3, 0xaa, 0xf0, 0x23, 0x05, 0x93, 0x5d, 0x30, 0xbc, 0x24,
	0x1e, 0x46, 0xcc, 0x2a, 0xcb, 0x63, 0x5b, 0xba, 0xd0, 0xd7, 0x72, 0xdf, 0x51, 0x79, 0xe2, 0x7a,
	0xcf, 0x91, 0x71, 0xc1, 0x69, 0xc8, 0xc2, 0xb3, 0x50, 0x08, 0x65, 0x5e, 0x8c, 0x56, 0xb5, 0x55,
	0x6c, 0x2f, 0x39, 0x72, 0x4d, 0x1e, 0x42, 0xad, 0x27, 0xfd, 0xe7, 0xc6, 0xc1, 0x04, 0x2d, 0x53,
	0xaa, 0x80, 0x14, 0x3a, 0x0d, 0x26, 0x48, 0xf7, 0xc1, 0x48, 0x0b, 0x5c, 0x9e, 0xb3, 0x98, 0x39,
	0xe7, 0x23, 0x58, 0xc1, 0x70, 0x20, 0x4f, 0x92, 0xe9, 0x41, 0x4d, 0x61, 0x27, 0xde, 0x04, 0xe9,
	0x00, 0xea, 0x67, 0x53, 0xdf, 0xd3, 0x2c, 0x9b, 0x70, 0x64, 0x19, 0x5f, 0x89, 0xf0, 0x7e, 0xbe,
	0xb2, 0x81, 0x64, 0x0b, 0xdd, 0xea, 0xf6, 0x1f, 0xb0, 0xf6, 0x3e, 0xe0, 0xd2, 0x16, 0x7c, 0xa6,
	0xab, 0x01, 0xe5, 0x88, 0xf9, 0xc8, 0x94, 0xaa, 0x34, 0x20, 0x0f, 0x00, 0xa6, 0xde, 0x00, 0xdd,
	0x38, 0x1a, 0x61, 0xa8, 0xce, 0x68, 0x0a, 0xe4, 0x54, 0x00, 0xe4, 0x3f, 0x90, 0x81, 0xcb, 0x83,
	0x0b, 0x94, 0x97, 0x5d, 0x76, 0xaa, 0x02, 0xe8, 0x04, 0x17, 0x48, 0x36, 0xc0, 0x98, 0x7a, 0x0c,
	0xc3, 0x58, 0xde, 0xb0, 0xe9, 0xa8, 0x88, 0x06, 0x50, 0xcf, 0x54, 0xff, 0x13, 0x57, 0x92, 0x2d,
	0x58, 0x0d, 0xf1, 0x5b, 0xec, 0x6a, 0xda, 0xfe, 0x12, 0xf0, 0xc7, 0x99, 0x3e, 0x6a, 0xc3, 0xfa,
	0x59, 0xe8, 0xdf, 0x7d, 0x6c, 0xec, 0x42, 0x63, 0x31, 0xff, 0xd6, 0x56, 0xae, 0x43, 0xbd, 0x83,
	0x1e, 0xeb, 0x0d, 0x33, 0xfc, 0xb4, 0x01, 0x24, 0x0b, 0xa6, 0x24, 0x7b, 0x3f, 0xcb, 0x50, 0x13,
	0x40, 0x07, 0xd9, 0x79, 0xd0, 0x43, 0xf2, 0x19, 0x60, 0x3e, 0x00, 0xc9, 0xa6, 0x7e, 0x62, 0x6d,
	0xbe, 0x36, 0x1f, 0xdf, 0x9c, 0x94, 0x16, 0xa2, 0x05, 0x41, 0x3d, 0x1f, 0x7f, 0x79, 0xd4, 0xda,
	0x28, 0xcd, 0xa3, 0xd6, 0x27, 0x28, 0x2d, 0x90, 0x37, 0x50, 0x51, 0x13, 0x85, 0xb4, 0xf4, 0x4f,
	0x16, 0x27, 0x5b, 0xf3, 0x9a, 0x6b, 0x4c, 0x15, 0xce, 0x2d, 0x9b, 0xa7, 0x50, 0xfb, 0x73, 0xf2,
	0x14, 0xea, 0xae, 0xa7, 0x05, 0xf2, 0x09, 0xcc, 0x4b, 0x7f, 0x11, 0xaa, 0x7f, 0x74, 0xd5, 0xfa,
	0xcd, 0xcd, 0x1b, 0x73, 0x2e, 0x79, 0x5d, 0x58, 0xc9, 0x9a, 0x83, 0x3c, 0xc9, 0xd1, 0xa3, 0x9b,
	0xad, 0xb9, 0x75, 0x5b, 0x5a, 0xf6, 0xd6, 0xe6, 0xb6, 0xc9, 0xeb, 0x89, 0xe6, 0xb4, 0xbc, 0x9e,
	0xe8, 0xce, 0x4b, 0xb5, 0x67, 0x1f, 0x83, 0x3c, 0xed, 0x39, 0x2f, 0x53, 0x9e, 0xf6, 0xbc, 0x37,
	0x85, 0x16, 0x0e, 0x8c, 0x2f, 0xf2, 0x55, 0xef, 0x1a, 0x72, 0x52, 0xbd, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x26, 0x71, 0x7b, 0xb4, 0x5f, 0x08, 0x00, 0x00,
}
